name: Update Official Shop

on:
  - push
  - pull_request

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run Script
        run: pnpm ts-node index.ts

      - name: Add File
        run: |
          git config --local user.email "81743021+mzakiyuddin@users.noreply.github.com"
          git config --local user.name "mzakiyuddin"
          git add .

      - name: Check is need to push
        id: check_status
        run: |
          STATUS=$(git status --porcelain | wc -l)
          echo "number of files that need to be committed:" $STATUS
          echo "::set-output name=STATUS::$STATUS"

      - name: Commit File
        if: steps.check_status.outputs.STATUS > 0
        run: |
          echo "status"
          now=$(date '+%Y-%m-%d %H:%M:%S')
          git commit -m "Auto Commit $now"

      - name: Push Changes
        if: steps.check_status.outputs.STATUS > 0
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
